# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gripper
  joint_model_group_pose: open
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - $(arg device_name)_synergy_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
# joint_state_controller:
$(arg device_name)_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
controller_list:
  - name: /$(arg robot_namespace)/control/$(arg device_name)_synergy_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - $(arg device_name)_synergy_joint
